name: First workflow

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Hello kir!!
        run: echo "Hello !!! from ${{github.workflow}} - event ${{github.event_name}} "
        
      - name: f
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context $JOB_CONTEXT "
          echo "DONE"

