name: First workflow

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      
      - name: Hello kir!!
        run: echo "Hello !!! from ${{github.workflow}} - event ${{github.event_name}} "

